ctfFramework: RootTheBox
ctfKey: FMATCyberLab2025
countryMapping: https://raw.githubusercontent.com/juice-shop/juice-shop/master/config/fbctf.yml
insertHints: free
insertHintUrls: free
insertHintSnippets: free
juiceShopUrl: ''
