countryMapping: https://raw.githubusercontent.com/juice-shop/juice-shop/master/config/fbctf.yml
ctfFramework: RootTheBox
ctfKey: FMATCyberLab2025
insertHintSnippets: free
insertHintUrls: free
insertHints: free
juiceShopUrl: https://juice-shop.herokuapp.com
