countryMapping: https://raw.githubusercontent.com/juice-shop/juice-shop/master/config/fbctf.yml
ctfFramework: RootTheBox
ctfKey: FMATCyberLab2025
insertHintSnippets: free
insertHintUrls: free
insertHints: free
juiceShopUrl: http://juice-shop-temp:3000
